let express=require("express")
const { adduser, login, islogin, isadmin } = require("../controlers/usercon")
const { restpwd, sendotp } = require("../controlers/resetpwdcont")
const { add, getall, upload, getbyid, addcomm, getbyretid, delprod, upd, updimg, regsearch } = require("../controlers/prodcont")
const { addcart, incqty, decqty, delcart, getcart } = require("../controlers/cartcon")
let rt=new express.Router()
rt.post("/reg",adduser)
rt.post("/login",login)
rt.post("/resetpwd",restpwd)
rt.get("/sendotp/:uid",sendotp)

rt.post("/addprod",upload.single("pimg"),islogin,isadmin,add)
rt.get("/prod",getall)
rt.post("/addcart",addcart)
rt.get("/inc/:cid",incqty)
rt.get("/dec/:cid",decqty)
rt.get("/del/:cid",delcart)
rt.get("/getcart/:uid",getcart)
rt.get("/getbyid/:pid",getbyid)
rt.put("/addcomm",addcomm)
rt.get("/getbyrt/:rid",getbyretid)
rt.delete("/del/:pid",delprod)
rt.put("/upd",upd)
rt.post("/updimg",upload.single("pimg"),updimg)
rt.get("/regsearch/:st",regsearch)
module.exports=rt