let express=require("express")
const { adduser, login } = require("../controller/usercon")
const { add, getall, getbycat, upd, del, pdm, admin, inspect, accept, like, dlike } = require("../controller/postcon")
let rt=new express.Router()
rt.post("/reg",adduser)
rt.post("/login",login)
rt.post("/addpost",add)
rt.get("/all",getall)
rt.get("/cat/:cat",getbycat)
rt.put("/upd",upd)
rt.delete("/del/:pid",del)
rt.get("/pdm/:uid",pdm)
rt.get("/admin",admin)
rt.put("/inspect",inspect)
rt.get("/approve/:pid",accept)
rt.put("/like",like)
rt.put("/dlike",dlike)
module.exports=rt